docs: add FAQ
charmbracelet/lipgloss pull request #189
Opened 2023-03-31 21:05 UTC by bashbunni

## Changes
- [x] answer "why isn't my border rendering correctly"
 - [x] answer "why isn't lip gloss displaying colors"

2023-04-06 17:48 UTC, meowgorithm requested changes

2023-04-06 19:33 UTC, meowgorithm commented on README.md
> +This is due to your encoding. If you aren't using UTF-8, you'll need to set an environment variable to be used by Lip Gloss.
Okay, I've updated this.

2023-05-23 18:52 UTC, bashbunni commented
Thank you!!

2023-05-23 18:53 UTC, meowgorithm approved these changes

2023-05-23 18:58 UTC, merged