Fix bugs with border size calculation
charmbracelet/lipgloss pull request #197
Opened 2023-04-29 13:51 UTC by mieubrisse

2023-04-29 14:53 UTC, meowgorithm requested changes
Thanks for this! Do you mind excluding the changes to .gitignore from this PR? We like to keep our PRs very specific, and there are a lot of rules in there (like node stuff) that don’t apply to this type of project.

2023-04-30 17:08 UTC, mieubrisse commented
Sure - just pushed. I'll open a separate PR with the VSCode and Idea one (I got hit by Git wanting to version control those)

2023-05-01 13:33 UTC, meowgorithm approved these changes

2023-05-01 13:37 UTC, merged

2023-05-01 13:37 UTC, meowgorithm commented
Thank you so much for this one!