Fix adding right padding to empty string
charmbracelet/lipgloss pull request #253
Opened 2024-01-26 02:28 UTC by mikelorant

An empty string could not have padding applied on the right side.

Issue: #252

2024-01-28 08:06 UTC, mikelorant commented
@meowgorithm Can I get approval to run the workflows? Thanks.

2024-01-30 09:05 UTC, mikelorant commented
Can I get someone from @charmbracelet to review this. Thanks.

2024-01-30 21:01 UTC, meowgorithm requested changes
Nice, this change makes sense to me. Do you mind adding a test as a proof?

2024-01-30 22:28 UTC, mikelorant commented
Tests have been added. Needed a little refactor for the test function but now lets us control what text we render. Unit tests all passing.

2024-01-30 22:37 UTC, meowgorithm commented
Nice work, LGTM!

2024-01-30 22:38 UTC, merged