feat: move tree to root
charmbracelet/lipgloss pull request #342
Opened 2024-07-23 22:11 UTC by caarlos0

closes #339 
closes #341

2024-07-23 23:23 UTC, bashbunni approved these changes

2024-07-24 13:25 UTC, aymanbagabas approved these changes

2024-07-24 14:53 UTC, meowgorithm commented
If you don't mind, going to look at a few last things today before we merge this one.

2024-08-01 16:07 UTC, bashbunni commented
Hey @meowgorithm any changes on this one?

2024-08-01 17:26 UTC, meowgorithm commented
Let’s get the tree examples back in as well — I'm looking at stuff now.

2024-08-01 18:34 UTC, bashbunni commented
@meowgorithm kk no rush. Just added the examples back

2024-08-01 18:41 UTC, meowgorithm approved these changes
Feeling good! Let's get this done ⚡️

2024-08-02 17:37 UTC, bashbunni commented
Removed `JoinVertical` from the final rendered element as it was writing unstyled whitespace to the final string. It does that by design to appropriately align elements in the block, but because it doesn't have access to the style, the whitespace can't be rendered. That said, I haven't seen this issue outside of the tree examples, so it's not pressing. 

If we did want to fix this we could replace this whitespace rendering with calling `Align` on the style which can render the whitespace properly or fix this with our compositor in a future version of lipgloss

2024-08-05 23:21 UTC, bashbunni requested changes
TODO before merge
- [ ] tidy godoc (some tree docs mention list)
- [x] show an example of unique styling of the root element (this might be broken)
- [ ] add tree info to `README.md`

2024-08-05 23:57 UTC, bashbunni commented
I thought the lipgloss root styling might be broken because if we do 

```go
ItemStyleFunc(func(children tree.Children, i int) lipgloss.Style {
    if children.At(i).Value() == "Nyx" {                          
        return itemStyle.Background(lipgloss.Color("#04B575"))    
    }                                                             
    return itemStyle                                              
})                                                                
```
we get 
```
%!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
``` 
because when we're on the root item, it's `children.At(-1)` which returns `nil`, then we attempt to call `Value()` on it. 

_As-is we will always need to do a root value check in `ItemStyleFunc` to avoid this..._

2024-08-06 00:02 UTC, bashbunni commented
We might even want to see about separating out `RootStyle` from `ItemStyle` 💭

2024-08-06 00:53 UTC, caarlos0 commented
> We might even want to see about separating out `RootStyle` from `ItemStyle` 💭

i think that makes more sense yes

2024-08-06 04:43 UTC, bashbunni commented on README.md
> +t := tree.New().
I can use the shorthand `tree.Root(".")...` and get rid of `New()` (not needed)

2024-08-19 15:15 UTC, bashbunni approved these changes

2024-08-19 16:15 UTC, aymanbagabas approved these changes

2024-08-19 18:33 UTC, meowgorithm approved these changes

2024-08-19 18:43 UTC, merged